kind: CronJob
apiVersion: batch/v1beta1
metadata:
  name: jmeter
  namespace: poc-redhat-babysitting
spec:
  schedule: 13 * * * *
  concurrencyPolicy: Allow
  suspend: false
  jobTemplate:
    metadata:
      creationTimestamp: null
    spec:
      template:
        metadata:
          name: jmeter
          creationTimestamp: null
        spec:
          volumes:
            - name: volume
              configMap:
                name: jmeter-file
                defaultMode: 420
          containers:
            - name: jmeter
              image: docker.io/justb4/jmeter
              args:
                - '-n'
                - '-t'
                - /volume/plan.jmx
                - '-j'
                - /tmp/jmeter.log
              resources: {}
              volumeMounts:
                - name: volume
                  mountPath: /volume
              envFrom:
                - secretRef:
                    name: asd
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
              imagePullPolicy: Always
          restartPolicy: Never
          terminationGracePeriodSeconds: 30
          dnsPolicy: ClusterFirst
          securityContext: {}
          schedulerName: default-scheduler
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
