kind: CronJob
apiVersion: batch/v1beta1
metadata:
  name: data-collector-cronjob
spec:
  schedule: 0 8/6 * * *
  concurrencyPolicy: Allow
  suspend: false
  jobTemplate:
    metadata:
        name: data-collector-cronjob
    spec:
      template:
        metadata:
          name: data-collector-cronjob
          creationTimestamp: null
        spec:
          containers:
            - name: data-collector
              image: nexus.agil.movistar.com.ar/nexus/repository/nexus-paas-digitales/cli:latest
              command:
                - bash
                - -c
                - |
                echo "Login openshift"
                oc login --token=$OC_TOKEN --server=$OC_SERVER --insecure-skip-tls-verify=true
                oc project $PROJECT

                echo "Obteniendo jvm_pid"
                jvm_pid=$(oc exec $PODNAME -- $JCMD_PATH | grep infinispan | awk '{print $1}';);

                echo "Recolectado informacion de Memoria y Thread"
                timestamp=$(date +%Y%m%d-%H%M)
                oc exec $PODNAME -- /bin/bash -c "mkdir -p $RESULT_PATH$PODNAME-$timestamp"
                oc exec $PODNAME -- /bin/bash -c "cp $RESULT_PATH$PODNAME/VM.native_memory-baseline.txt $RESULT_PATH$PODNAME-$timestamp/VM.native_memory-baseline.txt"
                oc exec $PODNAME -- /bin/bash -c "$JCMD_PATH $jvm_pid VM.info > $RESULT_PATH$PODNAME-$timestamp/VM.info.txt"
                oc exec $PODNAME -- /bin/bash -c "$JCMD_PATH $jvm_pid VM.native_memory detail.diff > $RESULT_PATH$PODNAME-$timestamp/VM.native_memory-detail.diff.txt"
                oc exec $PODNAME -- /bin/bash -c "$JCMD_PATH $jvm_pid GC.heap_info > $RESULT_PATH$PODNAME-$timestamp/GC.heap_info.txt"
                oc exec $PODNAME -- /bin/bash -c "$JCMD_PATH $jvm_pid GC.heap_dump $RESULT_PATH$PODNAME-$timestamp/heap-dump"
                oc exec $PODNAME -- /bin/bash -c "$JCMD_PATH $jvm_pid VM.metaspace > $RESULT_PATH$PODNAME-$timestamp/VM.metaspace.txt"
                oc exec $PODNAME -- /bin/bash -c "$JCMD_PATH $jvm_pid Thread.print > $RESULT_PATH$PODNAME-$timestamp/Thread.print.txt"

                echo "Recolectado  GC logs"
                oc exec $PODNAME -- /bin/bash -c "mkdir -p $RESULT_PATH$PODNAME-$timestamp/gc-logs"
                oc exec $PODNAME -- /bin/bash -c "cp /tmp/gc.log* $RESULT_PATH$PODNAME-$timestamp/gc-logs/"

                echo "Comprimiendo"
                oc exec $PODNAME -- /bin/bash -c "cd $RESULT_PATH && tar -zcvf $PODNAME-$timestamp.tar.gz $PODNAME-$timestamp"

                echo "Eliminando"
                oc exec $PODNAME -- /bin/bash -c "rm -fr $RESULT_PATH$PODNAME-$timestamp"

              envFrom:
                - configMapRef:
                    name: data-collector-config 
              resources: {}
              imagePullPolicy: Always
          restartPolicy: Never
