apiVersion: v1
kind: ConfigMap
metadata:
  name: data-collector-config
data:
  PODNAME: mimo-int-cache-5
  JCMD_PATH: /opt/infinispan/diag/bin/jcmd
  RESULT_PATH: /opt/infinispan/server/data/
  OC_TOKEN: sha256~2vVFDBfivVTqQ3r5k23-LS4dh20lEfqgX9fQkplo_EQ
  OC_SERVER: https://api.ocpnp.cuyorh.tcloud.ar:6443
  PROJECT: poc-redhat-babysitting

